export const why_tdd_quotes = [
    "To constrain ourselves to avoid over engineering",
    "To make it impossible to write untested code",
    "To make us think about the object interfaces",
    "To know when we're done",
    "To keep high coverage",
    "To communicate with intent to the rest of your team",
    "To make continuous incremental progress",
    "To spend less time manually testing",
    "To make code more testable",
    "Because it's easier to describe how should work",
    "than to make it work",
    "To keep focus on the requirements",
    "To avoid debugging",
    "To make debugging easier",
    "To be able to easily identify bugs when needed",
    "More cohesive objects",
    "Drives you to looser coupling and higher cohesion.",
    "It is harder to test highly coupled. non-cohesive code",
    "so TDD deters you from writing it",
    "Forces decoupling/reduced dependencies/better OO design",
    "Creates a living document/executable documentation",
    "To support refactoring",
    "Builds a safety new for your code",
    "To embrace/allow/give courage to change",
    "To convince the customer that the app works more of the time",
    "Time spent is more stable/consistent productivity/predictable",
    "Prevents growth of code debt",
    "Allows you to check in often",
    "Allows you to switch team members, even without finishing a feature",
    "Ability to delete code safely",
]